### ISSUE TITLE
Incorrect arenas assigned

### ISSUE THREAD

**Issue by sneak-it** [Headline22/Challenge#12]
I (believe) after version 1.1.0 this issue started occurring;

Upon joining server and joining team, you are put straight into arena 1. Even if you win arena 1 some rounds you get pushed back an arena. When I unload the plugin and join a team, I get put in the last arena and everything works fine again. I'll update when I figure out which version this started occurring in.

**Comment by sneak-it** [comment]
Update, it appears to have started on commit fee80c8

**Comment by Headline** [comment]
**Special thank you to blackhawk74** for letting me debug on his server
