### ISSUE TITLE
Not load on multi mod server

### ISSUE THREAD

**Issue by Deniel00** [Headline22/Challenge#24]
When want load on specificed map drop this error:
`[SM] Plugin disabled/multi1v1_hl_challenge.smx failed to load: Could not find required plugin "[Multi-1v1] Challenge".`

**Comment by Headline** [comment]
don’t change the plugins name

**Comment by Headline** [comment]
oh; it's a multi mod server? Meaning that Multi1v1 is not always loaded?

**Comment by Deniel00** [comment]
Yes.
But first load multi1v1 core then after load the Challenge plugin.

**Comment by Headline** [comment]
I suggest changing the plugin’s name back to hl_challenge and see if that fixes the issue

**Comment by Deniel00** [comment]
I will testing it, but i saw it use store.. :D but my server not using store.

**Comment by Headline** [comment]
If you don't use the store; it will leave the plugin unaffected

**Comment by Deniel00** [comment]
Later maybe rewrite to stamm system.

**Comment by Deniel00** [comment]
> 
> 
> If you don't use the store; it will leave the plugin unaffected

I re wrote to stamm, closed. Thanks
[https://github.com/Deniel00/Challenge](https://github.com/Deniel00/Challenge)

**Comment by Deniel00** [comment]
> 
> 
> If you don't use the store; it will leave the plugin unaffected

I re wrote to stamm, closed. Thanks
[https://github.com/Deniel00/Challenge](https://github.com/Deniel00/Challenge)
