### ISSUE TITLE
Could not find required plugin "store"

### ISSUE THREAD

**Issue by crashzk** [Headline22/Challenge#25]
List of plugins from my server shows an error in the plugin:
```
hl_challenge.smx ([Multi-1v1] Challenge): Could not find required plugin "store"
```
But in the error log there is no error.

Plugin needs the Store to work?

**Comment by Headline** [comment]
This plugin does not require store as a default. Are you using an edited version of this plugin? Make sure you're running the latest version

**Comment by crashzk** [comment]
The version I use on the server is the latest one, in case I just downloaded GitHub itself here:
```
 46 <Failed> "[Multi-1v1] Challenge" (1.1.5) by Headline
Errors:
hl_challenge.smx ([Multi-1v1] Challenge): Could not find required plugin "store"
```
Just downloaded it and send it to the server, I will download it again to check if I got any different version.

**Comment by crashzk** [comment]
I downloaded the version of GitHub I compiled and it was, no error now, thanks!
