### ISSUE TITLE
BUG SPECTATE

### ISSUE THREAD

**Issue by NexoIDG** [Headline22/Challenge#7]
When i challenge on my server and im spectate and i win challenge , plugin  teleport me in Arena 1 from Spectate , please fix this

**Comment by Headline** [comment]
Would a proper fix be to nit allow spectator players challenge since they shouldn't be able to anyway?

**Comment by NexoIDG** [comment]
How can i restrict spectators to use !challenge ?

Pe 10 ian. 2017 01:44, "Michael Flaherty" <notifications@github.com> a
scris:

Would a proper fix be to nit allow spectator players challenge since they
shouldn't be able to anyway?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Headline22/Challenge/issues/7#issuecomment-271443848>,
or mute the thread

**Comment by Headline** [comment]
I'll edit the plugin behavior. One second...

**Comment by NexoIDG** [comment]
Ok , i wait an answer when you finish

**Comment by Headline** [comment]
Okay, test this branch: https://github.com/Headline22/Challenge/tree/fix-spectateglitch and see if it fixes this issue. Players shouldn't be able to challenge when in spectator now, and players can't challenge spectators either

**Comment by NexoIDG** [comment]
Another bug , if im Arena 8 for example and i challenge Arena 1 and i win ,
im going to Arena 1 not Arena 8 back

**Comment by Headline** [comment]
Did the new branch fix the other issue, though?????

**Comment by NexoIDG** [comment]
Bug with spectate is now fixed
I retry this bug with challenge arena 1 and not everytime im go arena 1
when i win challenge , is a rare bug

Pe 10 ian. 2017 3:46 a.m., "Michael Flaherty" <notifications@github.com> a
scris:

**Comment by Headline** [comment]
Post a new issue so we can talk about that one on another thread.
