### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by NexoIDG** [Headline22/Challenge#9]
Another bug , if im Arena 8 for example and i challenge Arena 1 and i win , im going to Arena 1 not Arena 8 back.I retry this bug with challenge arena 1 and not everytime im go arena 1 when i win challenge , is a rare bug

**Comment by Headline** [comment]
Bug is definitely confirmed. Some times players (whether they win or lose) get sent up to arena 1.

**Comment by NexoIDG** [comment]
And solution ?

Pe 10 ian. 2017 21:44, "Michael Flaherty" <notifications@github.com> a
scris:

**Comment by NexoIDG** [comment]
UP any solution ?

**Comment by Technoblazed** [comment]
Typing "UP" doesn't doing anything, this is github. Someone will find a solution eventually.

**Comment by NexoIDG** [comment]
Ok , srry mate

**Comment by Headline** [comment]
If it's bad for now change the save old arenas cvar so that anyone who challenges won't be sent to a higher arena. Unless you'd rather live with the bug. I'm having troubling figuring out the solution to this issue, hopefully we can figure it out soon.

**Comment by Headline** [comment]
Please try the latest version and see if the latest commit has fixed this issue

**Comment by Headline** [comment]
Can anyone else confirm?

**Comment by NexoIDG** [comment]
It s ok now

On Tue, Jan 17, 2017 at 10:39 AM, Michael Flaherty <notifications@github.com
